/**
 * Slack Integration Service
 * Handles OAuth and posting summaries.
 */

const SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN || "";

export async function postToSlack(channelId: string, text: string) {
    if (!SLACK_BOT_TOKEN) {
        console.warn("⚠️ SLACK_BOT_TOKEN not found. Mocking Slack post.");
        return { success: true, ts: Date.now().toString() };
    }

    try {
        const response = await fetch("https://slack.com/api/chat.postMessage", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${SLACK_BOT_TOKEN}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                channel: channelId,
                text
            }),
        });

        const data = await response.json();
        return { success: data.ok, ts: data.ts };
    } catch (err) {
        console.error("❌ Slack API error:", err);
        throw err;
    }
}

export async function shareMeetingSummary(meetingTitle: string, summary: string, channelId: string) {
    const text = `*New Meeting Summary:* _${meetingTitle}_\n\n${summary}\n\n_Generated by Zap-Bot_`;
    return postToSlack(channelId, text);
}
